# Generated by Django 2.1 on 2019-01-22 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('photo', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(max_length=120)),
                ('full_news', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Image')),
            ],
        ),
    ]
