# Generated by Django 2.1 on 2019-01-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0003_auto_20190122_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_news',
            field=models.CharField(max_length=200000000000, null=True),
        ),
    ]
