# Generated by Django 2.1 on 2019-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0004_auto_20190122_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
