# Generated by Django 2.1 on 2019-01-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0006_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='topics',
        ),
    ]
