# Generated by Django 2.1 on 2019-01-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0007_auto_20190124_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='news',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
