# Generated by Django 2.1 on 2019-01-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0008_auto_20190124_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='full_news',
        ),
        migrations.AddField(
            model_name='news',
            name='full_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='publishedDate',
            field=models.DateField(null=True),
        ),
    ]
