# Generated by Django 2.1 on 2019-01-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0009_auto_20190125_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
