# Generated by Django 2.1 on 2019-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0010_auto_20190125_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_pk', models.IntegerField(default=0)),
                ('topics', models.CharField(max_length=50)),
            ],
        ),
    ]
