# Generated by Django 2.1 on 2019-01-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0013_auto_20190125_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
