# Generated by Django 2.1 on 2019-01-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0014_news_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sentiment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
